export const asset = (path) => `/assets/original/${path}`;
export const roles = [
  {
    id: 'guia',
    name: 'Guía',
    verb: 'Explora el mapa',
    icon: 'Compass',
    image: 'Guia',
    audio: 'Guia',
    description:
      'Deberás observar detalladamente el mapa e indicarle al Huaquero dónde debe buscar los misteriosos símbolos que aparecen en el mapa; tendrán que reaccionar rápido antes de que el rastro se pierda.',
  },
  {
    id: 'huaquero',
    name: 'Huaquero',
    verb: 'Encuentra los símbolos',
    icon: 'ScanLine',
    image: 'Huaquero',
    audio: 'Huaquero',
    description:
      'Con ayuda de la cámara de tu dispositivo, explora los lugares claves; toca los símbolos para guardarlos. Enséñaselos al Intérprete para que él pueda descifrarlos. ¡Ten cuidado!, solo podrás tocar los símbolos indicados.',
  },
  {
    id: 'interprete',
    name: 'Intérprete',
    verb: 'Revela el significado',
    icon: 'Layers',
    image: 'Interprete',
    audio: 'Interprete',
    description:
      'Utiliza los símbolos que el Huaquero encuentre para traducirlos. Para ello, deberás encontrar los pares de estos y solo entonces revelarás el significado de cada símbolo. ¡Ten cuidado!, no podrás revelar distintos símbolos.',
  },
  {
    id: 'antropologo',
    name: 'Antropólogo',
    verb: 'Descifra las palabras',
    icon: 'Fingerprint',
    image: 'Antropologo',
    audio: 'Antro',
    description: 'Resuelve el anagrama, ordena las palabras para desbloquear el código secreto.',
  },
];
export const stories = [
  {
    id: 1,
    name: 'Cuencos rituales',
    short: 'Cuencos',
    video: 'Cuencos',
    symbols: [1, 2, 3, 4],
    distractors: [5, 6, 7, 8],
    places: [1, 2, 3, 4],
    anagrams: ['tuariles', 'tear', 'alfarosre', 'potiem'],
    answers: ['rituales', 'arte', 'alfareros', 'tiempo'],
    words: ['rituales', 'arte', 'alfareros', 'tiempo'],
    sentence: [
      'Los cuencos ',
      ' nos revelan la profunda conexión entre el ',
      ', la cultura y la preservación del legado ancestral de los ',
      ' nariñenses a través del ',
      '.',
    ],
  },
  {
    id: 2,
    name: 'Las alcarrazas',
    short: 'Alcarrazas',
    video: 'Alcarrazas',
    symbols: [13, 14, 15, 16],
    distractors: [8, 1, 2, 9],
    places: [1, 4, 2, 5],
    anagrams: ['turascul', 'masfor', 'blospue', 'gadole'],
    answers: ['culturas', 'formas', 'pueblos', 'legado'],
    words: ['culturas', 'formas', 'pueblos', 'legado'],
    sentence: [
      'Las alcarrazas, testigos de antiguas ',
      ' malagana y yotoco, nos revelan en sus ',
      ' antropomorfas, zoomorfas y fitomorfas, la asombrosa creatividad y conexión con la naturaleza de estos ',
      ' ancestrales, un ',
      ' que apreciamos y preservamos para las generaciones venideras.',
    ],
  },
  {
    id: 3,
    name: 'Volantes de huso',
    short: 'Volantes',
    video: 'Volantes',
    symbols: [9, 10, 11, 12],
    distractors: [3, 15, 14, 7],
    places: [3, 5, 2, 4],
    anagrams: ['braso', 'loshi', 'toriahis', 'tefuen'],
    answers: ['obras', 'hilos', 'historia', 'fuente'],
    words: ['obras', 'hilos', 'historias', 'fuente'],
    sentence: [
      'Los volantes de huso, más que simples herramientas, son auténticas ',
      ' de arte que tejían no solo ',
      ' sino también ',
      ' de la cultura quimbaya y yotoco. Sus diseños celestiales y naturales inspiraron incluso al reconocido artista colombiano Omar Rayo, quien vio en ellos una ',
      ' inagotable de creatividad geométrica.',
    ],
  },
  {
    id: 4,
    name: 'Urnas funerarias',
    short: 'Urnas',
    video: 'Urnas',
    symbols: [5, 6, 7, 8],
    distractors: [3, 14, 12, 2],
    places: [5, 1, 2, 3],
    anagrams: ['tuariles', 'naur', 'incianfa', 'zacru'],
    answers: ['rituales', 'urna', 'infancia', 'cruza'],
    words: ['rituales', 'urna', 'infancia', 'cruza'],
    sentence: [
      'Las urnas funerarias, guardianas de secretos ancestrales, nos sumergen en los ',
      ' y creencias de civilizaciones pasadas. Desde las antropomorfas Quimbayas hasta la conmovedora ',
      ' infantil, y la figura Sonso que evoca la ',
      ', cada urna revela una historia única que ',
      ' los siglos y nos conecta con la diversidad cultural de épocas olvidadas.',
    ],
  },
  {
    id: 5,
    name: 'Sonidos ancestrales',
    short: 'Silbatos',
    video: 'Silbatos',
    symbols: [17, 18, 19, 20],
    distractors: [1, 4, 8, 12],
    places: [3, 4, 1, 5],
    anagrams: ['dosniso', 'zaspie', 'toriahis', 'batosil'],
    answers: ['sonidos', 'piezas', 'historia', 'silbato'],
    words: ['sonidos', 'piezas', 'historias', 'silbato'],
    sentence: [
      'Los silbatos, portadores de ',
      ' ancestrales, nos sumergen en rituales y festividades olvidadas. En el Museo Lili, seis de estas ',
      ' únicas nos revelan ',
      ' intrigantes, como el ',
      ' zoomorfo del ave Tulcán, cuyo sonido estaba destinado a los rituales espirituales de los Andes.',
    ],
  },
];
export const symbolImage = (id) => asset(`Traductor/simbolos/simbolo${id}.png`);
export const storyFor = (id) => stories.find((s) => s.id === Number(id)) || stories[0];
